AllCops:
  Exclude:
    - '.git/**/*'
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'db/schema.rb'
Layout/LineLength:
  IgnoredPatterns: ['\A\s*#']
Style/Documentation:
  Enabled: false
Style/EmptyMethod:
  EnforcedStyle: expanded
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true
Layout/SpaceAroundMethodCallOperator:
  Enabled: true
Lint/DeprecatedOpenSSLConstant:
  Enabled: true
Lint/RaiseException:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true
Style/ExponentialNotation:
  Enabled: true
Style/SlicingWithRange:
  Enabled: true
Metrics/ClassLength:
  Exclude:
    - 'test/**/*_test.rb'
Metrics/BlockLength:
  Exclude:
    - 'test/**/*_test.rb'
Metrics/AbcSize:
  Exclude:
    - 'test/**/*_test.rb'
Metrics/MethodLength:
  Exclude:
    - 'test/**/*_test.rb'
    - 'db/**/*.rb'
