development:
  clients:
    default:
      database: categories_api_development
      hosts:
        - localhost:27017
test:
  clients:
    default:
      database: categories_api_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
production:
  clients:
    default:
      database: categories_api_production
      hosts:
        - localhost:27017
