#!/bin/bash

function __configure {
  cd /opt/categories-api

  source "$HOME/.rvm/scripts/rvm"

  bundle config path vendor/bundle
}

function __main {
  RAILS_ENV=production bundle install --jobs 4 --retry 3
  RAILS_ENV=production bundle exec rake db:mongoid:create_indexes
}

__configure && __main
