#!/bin/bash

function __configure {
  gpg --keyserver hkp://pool.sks-keyservers.net \
      --recv-keys \
      409B6B1796C275462A1703113804BB82D39DC0E3 \
      7D2BAF1CF37B13E2069D6956105BD0E739499BDB

  if [ $? -ne 0 ]; then
    curl -sSL https://rvm.io/mpapis.asc | gpg --import -
    curl -sSL https://rvm.io/pkuczynski.asc | gpg --import -
  fi

  curl -sSL https://get.rvm.io | bash -s stable
}

function __main {
  [[ -s "$HOME/.rvm/scripts/rvm" ]] || __configure

  source /home/ubuntu/.rvm/scripts/rvm

  rvm install 2.6

  gem install rake
  gem install bundler
}

__main
