#!/bin/bash

function __configure {
  sudo apt-get update
  sudo apt-get install -y ruby wget
}

function __main {
  wget 'https://aws-codedeploy-ap-south-1.s3.ap-south-1.amazonaws.com/latest/install'

  chmod +x ./install

  sudo ./install auto

  sudo service codedeploy-agent start
}

__configure && __main
